### ISSUE TITLE
Discuss: I have some advices for improve this program

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/flink-connector-cnosdb#1]
### Build error message lazily.

Here we can almost always skip building a string as error message:

https://github.com/cnosdb/flink-connector-cnosdb/blob/68f0c8ac2e1a2ce51c23dffc89ab85bf83d82e23/src/main/java/com/cnosdb/flink/streaming/connectors/cnosdb/CnosDB.java#L28-L29

For example:

```java
Preconditions.checkNotNull(HttpUrl.parse(urlString), "url:%s is invalid", urlString).newBuilder();
```

### Check URL when initializing

Here we can move `HttpUrl` instantiation in the start of this connector, such as the constructor.

```java
CnosDB(CnosDBConfig config) {
    this.client = new OkHttpClient();
    this.cnosDBConfig = config;
    String urlString = Preconditions.checkNotNull(cnosDBConfig.getUrl(), "url can not be null");
    this.httpUrl = Preconditions.checkNotNull(HttpUrl.parse(urlString), "url:%s is invalid", urlString);
}
```

### Call `Response::close()` manually

```java
response.close();
```

**Comment by ZuoTiJia** [comment]
fixed in https://github.com/cnosdb/flink-connector-cnosdb/commit/7f52156666a9e98587649343da974bb4a9a59940
